version: '3'

services:
  postgres-tgl:
      image: "postgres"
      container_name: postgres-tgl
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: lucy
        POSTGRES_DATABASES: barber
        HOSTNAME: localhost
      volumes:
      - postgresData:/var/lib/postgresql/data

volumes:
  postgresData:
    
#Crear volumen
# docker volume create postgresData
#Iniciar su docker compose 
  # Ubicarse en la ruta donde este el archivo docker-compose.yml
# docker-compose -p postgresTGL up -d