version: 2.1
jobs:
  run_tests:
    docker:
     - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run tests
          command: ./node_modules/ava/bin/ava test/
      - store_test_results:
         path: test-results
      - store_artifacts:
         path: test-results
workflows:
  build_tests:
    jobs:
      - run_tests
        
